spring.application.name=timbra-cartellino-backend

spring.data.redis.host=${db_url}
spring.data.redis.port=${db_port}

spring.data.redis.database=${db_identify}
spring.data.redis.username=${db_username}
spring.data.redis.password=${db_password}

spring.data.redis.ssl.enabled=true

logging.level.org.springframework.data.redis=DEBUG
logging.level.io.lettuce.core=DEBUG